### ISSUE TITLE
Make the master release process on AppVeyor create a release on GitHub

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#47]
We have the @radical-bot user that can be used to create a TAG and push is back to the repo, in order to make it work we need to generate a security token for the user and change the AppVeyor config adding the following: https://www.appveyor.com/docs/deployment/github
- [x] Radical
- [x] Radical.Windows
- [x] Radical.Design
- [x] Radical.Windows.Presentation
- [x] Radical.Windows.Presentation.CastleWindsor
- [x] Radical.Windows.Presentation.Autofac
- [x] Radical.Windows.Presentation.Unity2
- [x] Radical.Windows.Presentation.Unity3

The changes that need to be done are:
- add `skip_tags: true` to the `develop` and `master` config so that a tag doesn't trigger a build
- add the following to the `master` deploy section:

```
  - provider: GitHub    
    release: $(GitVersion_NuGetVersion)
    description: 'Release v$(GitVersion_NuGetVersion)'
    auth_token:
      secure: 2ijF4OfPYfIUTunubL/Z04ogADL9sx/gKW1jMRNJnAa1OpHZpSvCKmP0gvNs8C7h
    artifact: /.*\.nupkg/, src\build\Release.zip
    on:
      branch: master
```

Related to https://github.com/RadicalFx/housekeeping/issues/35

**Comment by mauroservienti** [comment]
Was:

```
environment:
  access_token:
    secure: <token here>

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "...."
  - git config --global user.name "Radical Build"
  - git git tag -a v%GitVersion_NuGetVersion% -m "Release v%GitVersion_NuGetVersion%"
  - git push --follow-tags
```
